const menuCategory = [
  "kien-truc-cong-trinh",
  "noi-that",
  "quy-hoach",
  "sinh-vien",
  "bao-ton",
  "canh-quan",
  "doi-tac-kinh-doanh",
  "quan-li-nha-nuoc",
];
const doiTacKinhDoanh = {
  category: "doi-tac-kinh-doanh",
  menu: [
    { content: "Đối tác kinh doanh", href: "/" },
    { content: "Đối tác kinh doanh", href: "/" },
    { content: "Đối tác kinh doanh", href: "/" },
    { content: "Đối tác kinh doanh", href: "/" },
    { content: "Đối tác kinh doanh", href: "/" },
    { content: "Đối tác kinh doanh", href: "/" },
  ],
};
const variants = [
  {
    color: "red",
    icon: `<img src="./assets/svg/home/red.svg" alt='' />`,
  },
  {
    color: "yellow",
    icon: `<img src="./assets/svg/home/yellow.svg" alt='' />`,
  },
  {
    color: "lightgreen",
    icon: `<img src="./assets/svg/home/lightgreen.svg" alt='' />`,
  },
  {
    color: "green",
    icon: `<img src="./assets/svg/home/green.svg" alt='' />`,
  },
  {
    color: "blue",
    icon: `<img src="./assets/svg/home/blue.svg" alt='' />`,
  },
  {
    color: "brown",
    icon: `<img src="./assets/svg/home/brown.svg" alt='' />`,
  },
  {
    color: "orange",
    icon: `<img src="./assets/svg/home/orange.svg" alt='' />`,
  },
  {
    color: "gray",
    icon: `<img src="./assets/svg/home/gray.svg" alt='' />`,
  },
];
const dataSlideResources = [
  {
    text: "Kiến trúc công trình",
    follow: false,
  },
  {
    text: "Nội thất",
    follow: false,
  },
  {
    text: "Quy hoạch",
    follow: false,
  },
  {
    text: "Sinh viên",
    follow: false,
  },
  {
    text: "Bảo tồn",
    follow: true,
  },
  {
    text: "Cảnh quan",
    follow: true,
  },
  {
    text: "Quản lí nhà nước",
    follow: true,
  },
  {
    text: "Đối tác kinh doanh",
    follow: true,
  },
];
let dataMajor = [
  { text: "Triển Khai Kiến Trúc Công Trình", follow: false },
  { text: "Triển Khai Kỹ Thuật", follow: false },
  { text: "Quy Hoạch Tổng Mặt Bằng", follow: false },
  { text: "Đồ Án Đoạt Giải", follow: false },
  { text: "Bảo Tồn Di Sản", follow: false },
  { text: "Thiết kế cảnh quan", follow: false },
  { text: "Quản Lý Địa Phương", follow: false },
  { text: "Đối Tác Kiến Trúc", follow: false },
  { text: "Triển Khai Kiến Trúc Công Trình", follow: true },
  { text: "Triển Khai Kỹ Thuật", follow: true },
  { text: "Quy Hoạch Tổng Mặt Bằng", follow: true },
  { text: "Đồ Án Đoạt Giải", follow: true },
  { text: "Bảo Tồn Di Sản", follow: true },
  { text: "Thiết kế cảnh quan", follow: true },
  { text: "Quản Lý Địa Phương", follow: true },
  { text: "Đối Tác Kiến Trúc", follow: true },
  { text: "Triển Khai Kiến Trúc Công Trình", update: true },
  { text: "Triển Khai Kỹ Thuật", update: true },
  { text: "Quy Hoạch Tổng Mặt Bằng", update: true },
  { text: "Đồ Án Đoạt Giải", update: true },
  { text: "Bảo Tồn Di Sản", update: true },
  { text: "Thiết kế cảnh quan", update: true },
  { text: "Quản Lý Địa Phương", update: true },
  { text: "Đối Tác Kiến Trúc", update: true },
  { text: "Triển Khai Kiến Trúc Công Trình", follow: false },
  { text: "Triển Khai Kỹ Thuật", follow: false },
  { text: "Quy Hoạch Tổng Mặt Bằng", follow: false },
  { text: "Đồ Án Đoạt Giải", follow: false },
  { text: "Bảo Tồn Di Sản", follow: false },
  { text: "Thiết kế cảnh quan", follow: false },
  { text: "Quản Lý Địa Phương", follow: false },
  { text: "Đối Tác Kiến Trúc", follow: false },
];
const dataCollections = [
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
  {
    img: "./assets/image/collection-1.png",
    star: 4.8,
    review: 20,
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "",
  },
];

const dataDocuments = [
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
  {
    img: "./assets/image/document-1.png",
    download: 300,
    title: "Thư viện bàn và ghế sofa tiếp khách văn phòng đầy đủ",
    href: "/",
  },
];

const dataTrademarkNoiThat = [
  { img: "./assets/image/trademark-1.png", width: "25%" },
  { img: "./assets/image/trademark-2.png", width: "50%" },
  { img: "./assets/image/trademark-3.png", width: "25%" },
  { img: "./assets/image/trademark-4.png", width: "100%" },
  { img: "./assets/image/trademark-5.png", width: "70%" },
  { img: "./assets/image/trademark-6.png", width: "30%" },
  { img: "./assets/image/trademark-7.png", width: "45%" },
  { img: "./assets/image/trademark-8.png", width: "55%" },
  { img: "./assets/image/trademark-1.png", width: "25%" },
  { img: "./assets/image/trademark-2.png", width: "50%" },
  { img: "./assets/image/trademark-3.png", width: "25%" },
  { img: "./assets/image/trademark-4.png", width: "100%" },
  { img: "./assets/image/trademark-5.png", width: "70%" },
  { img: "./assets/image/trademark-6.png", width: "30%" },
  { img: "./assets/image/trademark-7.png", width: "45%" },
  { img: "./assets/image/trademark-8.png", width: "55%" },
];

const dataTrademarkNgoaiThat = [
  { img: "./assets/image/trademark-1.png", width: "25%" },
  { img: "./assets/image/trademark-2.png", width: "50%" },
  { img: "./assets/image/trademark-3.png", width: "25%" },
  { img: "./assets/image/trademark-4.png", width: "100%" },
  { img: "./assets/image/trademark-5.png", width: "70%" },
  { img: "./assets/image/trademark-6.png", width: "30%" },
  { img: "./assets/image/trademark-7.png", width: "45%" },
  { img: "./assets/image/trademark-8.png", width: "55%" },
  { img: "./assets/image/trademark-1.png", width: "25%" },
  { img: "./assets/image/trademark-2.png", width: "50%" },
  { img: "./assets/image/trademark-3.png", width: "25%" },
  { img: "./assets/image/trademark-4.png", width: "100%" },
  { img: "./assets/image/trademark-5.png", width: "70%" },
  { img: "./assets/image/trademark-6.png", width: "30%" },
  { img: "./assets/image/trademark-7.png", width: "45%" },
  { img: "./assets/image/trademark-8.png", width: "55%" },
];

const dataTrademarkNoiTangCanhQuan = [
  { img: "./assets/image/trademark-1.png", width: "25%" },
  { img: "./assets/image/trademark-2.png", width: "50%" },
  { img: "./assets/image/trademark-3.png", width: "25%" },
  { img: "./assets/image/trademark-4.png", width: "100%" },
  { img: "./assets/image/trademark-5.png", width: "70%" },
  { img: "./assets/image/trademark-6.png", width: "30%" },
  { img: "./assets/image/trademark-7.png", width: "45%" },
  { img: "./assets/image/trademark-8.png", width: "55%" },
  { img: "./assets/image/trademark-1.png", width: "25%" },
  { img: "./assets/image/trademark-2.png", width: "50%" },
  { img: "./assets/image/trademark-3.png", width: "25%" },
  { img: "./assets/image/trademark-4.png", width: "100%" },
  { img: "./assets/image/trademark-5.png", width: "70%" },
  { img: "./assets/image/trademark-6.png", width: "30%" },
  { img: "./assets/image/trademark-7.png", width: "45%" },
  { img: "./assets/image/trademark-8.png", width: "55%" },
];
